services:
  stockfish:
    image: ivangabrielle/dockfish:latest
    container_name: stockfish
    ports:
      - "4000:4000"
    restart: on-failure
    depends_on:
      - chessdqn
    networks:
      - chess-network

  chesscrawler:
    image: jackhlay/chesscrawler:dev
    container_name: chesscrawler
    ports:
      - "3000:3000"
    depends_on:
      - stockfish
    restart: on-failure
    networks:
      - chess-network

  chessdqn:
    image: jackhlay/chessdqn:dev
    container_name: chessdqn
    ports:
      - "8000:8000"
    networks:
      - chess-network

networks:
  chess-network:
    driver: bridge