services:
  stockfish:
    image: ivangabriele/dockfish:15
    container_name: stockfish
    ports:
      - "4000:4000"
    restart: on-failure
    depends_on:
      - chessdqn
    networks:
      - chess-network
    environment:
      - PORT=4000

  chessdqn:
    image: jackhlay/chessdqn:0.1.0
    container_name: chessdqn
    ports:
      - "8000:8000"
    networks:
      - chess-network

networks:
  chess-network:
    driver: bridge