name: Publish Docker Images
on: 
  push:
    branches:
      - main  # Trigger only on pushes to the main branch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # Set up QEMU for multi-platform builds
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      
      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Debug: List repository files
      - name: List repository files
        run: ls -R

      # Build and push the DQN Docker image
      - name: Build and push DQN Image
        uses: docker/build-push-action@v6.10.0
        with:
          context: .  # Updated path
          push: true
          file: Python/Dockerfile  # Adjust if Dockerfile is in Python folder
          tags: ${{ secrets.DOCKER_USERNAME }}/chessdqn:${{ github.sha }}

      # Build and push the Crawler Docker image
      - name: Build and push Crawler Image
        uses: docker/build-push-action@v6.10.0
        with:
          context: .
          push: true
          file: Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/chesscrawler:${{ github.sha }}
