name: Publish Docker Images

on: 
  push:
    branches:
      - main  # Trigger only on pushes to the main branch

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKERHUB_REPOSITORY: ${{ secrets.DOCKER_USERNAME }}/chesscrawler
  DOCKER_IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      # Step 3: Set up QEMU for multi-platform builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Step 4: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Debug: List repository files (optional)
      - name: List repository files
        run: ls -R

      # Step 5: Build and push the Crawler Docker image
      - name: Build and push Crawler Image
        uses: docker/build-push-action@v6.10.0
        with:
          context: .
          push: true
          file: Dockerfile
          tags: ${{ env.DOCKERHUB_REPOSITORY }}:${{ env.DOCKER_IMAGE_TAG }}

      # Step 6: Build and push the DQN Docker image
      - name: Build and push DQN Image
        uses: docker/build-push-action@v6.10.0
        with:
          context: ./Python
          push: true
          file: Python/Dockerfile  # Adjust if Dockerfile is in Python folder
          tags: ${{ secrets.DOCKER_USERNAME }}/chessdqn:${{ github.sha }}

  release:
    name: Release Docker Images
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Push the built images to Docker Hub
      - name: Push Docker Images to Docker Hub
        run: |
          docker push ${{ env.DOCKERHUB_REPOSITORY }}:${{ env.DOCKER_IMAGE_TAG }}
          docker push ${{ secrets.DOCKER_USERNAME }}/chessdqn:${{ github.sha }}

      # Step 4: Update Docker Hub Readme
      - name: Update Docker Hub Readme
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKERHUB_REPOSITORY }}
